[build]
  publish="public"
  command="gatsby build"

[[plugins]]
  package = "netlify-plugin-image-optim"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "public"

[context.production]
  environment = { NODE_VERSION = "20.19.3", NETLIFY_USE_YARN = "true" }
